### ISSUE TITLE
Crash on Windows when running the Readme examples

### ISSUE THREAD

**Issue by lanner17** [eclipse-zenoh/zenoh-backend-filesystem#4] opened 2021-11-19 21:09 UTC
I am trying to run the examples from the Readme file but, the zenoh router stops unexpectedly after I loaded the file backend. The file backend seems to load, but the router terminates when I query with 

`curl http://localhost:8000/@/router/local/plugin/storages/backend/*`

to see which backends are loaded.

I start the server with 
```
set ZBACKEND_FS_ROOT=C:/Users/jnswart/Downloads/zenoh/storage
set RUST_LOG=debug
zenohd.exe --backend-search-dir=.\
```
From another terminal:
```
curl -X PUT -H content-type:application/properties http://localhost:8000/@/router/local/plugin/storages/backend/fs
curl http://localhost:8000/@/router/local/plugin/storages/backend/*
```
The last curl command causes the server to terminate - apparently with no error. Also note that I do not use single quotes for the curl arguments. If I do, the server does not load the file backend (It is Windows 10). This is just a side note as this is probably a router issue.

```
[2021-11-19T20:54:21Z DEBUG zbackend_fs] Using root dir: C:/Users/jnswart/Downloads/zenoh/storage
[2021-11-19T20:54:21Z DEBUG zenoh] New workspace with prefix: Some(Path { p: "/@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs" })
[2021-11-19T20:54:21Z DEBUG zenoh::workspace] eval on /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::resource] Register resource /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::queries] Register queryable /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs for Face{2, BCF6521B99D3404D980D4377BB463FD5}
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::queries] Register router queryable /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs (router: BCF6521B99D3404D980D4377BB463FD5)
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::queries] Register peer queryable /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs (peer: BCF6521B99D3404D980D4377BB463FD5)
[2021-11-19T20:54:21Z DEBUG zenoh::workspace] subscribe on storage/*
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::resource] Register resource /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs/storage/
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::resource] Register resource /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs/storage/*
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::pubsub] Register subscription /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs/storage/* for Face{2, BCF6521B99D3404D980D4377BB463FD5}
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::pubsub] Register router subscription /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs/storage/* (router: BCF6521B99D3404D980D4377BB463FD5)
[2021-11-19T20:54:21Z DEBUG zenoh::net::routing::pubsub] Register peer subscription /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/fs/storage/* (peer: BCF6521B99D3404D980D4377BB463FD5)
[2021-11-19T20:54:27Z INFO  tide::log::middleware] <-- Request received
[2021-11-19T20:54:27Z DEBUG zenoh::net::routing::queries] Route query Face{1, BCF6521B99D3404D980D4377BB463FD5}:1 for res /@/router/BCF6521B99D3404D980D4377BB463FD5/plugin/storages/backend/*
[2021-11-19T20:54:27Z DEBUG zenoh::net::routing::queries] Received final reply Face{1, BCF6521B99D3404D980D4377BB463FD5}:2 from Face{0, BCF6521B99D3404D980D4377BB463FD5}
```
If I do not load the file backend, the router does not terminate, but responds that the memory storage is present (as expected)
I am just wondering what the reason is for the termination is as there seems to be no error. It could be a zenoh router issue, but it seems to be triggered by the file backend.

**Comment by JEnoch** [comment] 2021-11-22 09:39
It might be a crash caused by the router and the plugin using different versions of Rust or of some dependencies. The root cause being that Rust doesn't have a stable ABI, leading to possible SIGSEV crash if `zenohd` and the plugin use different memory mapping for a same type.

Which exact versions of `zenohd` and of the file backend are you using ?
You can check router's version with `zenohd --version`.
For the backend, look at such log when the backend library is loaded by the router:
`2021-11-22T09:31:32Z DEBUG zbackend_fs] FileSystem backend v... built with rustc ...`

**Comment by lanner17** [comment] 2021-11-22 12:37
That explanation makes sense and I fully expected that, however, it seems to be the exact same versions
zenohd :

`The zenoh router v0.5.0-beta.8 built with rustc 1.52.0-nightly (107896c32 2021-03-15)`

The file backend :
```
[2021-11-22T12:18:18Z DEBUG zplugin_storages] Create backend fs using \\?\C:\Users\jnswart\Downloads\zenoh\zbackend_fs.dll
[2021-11-22T12:18:18Z DEBUG zbackend_fs] FileSystem backend v0.5.0-beta.8 built with rustc 1.52.0-nightly (107896c32 2021-03-15)
```

**Comment by lanner17** [comment] 2021-12-17 14:51
To get around the ABI issue between zenoh and zenoh-backend-filesystem, I built both projects with Rust 1.57 on a Windows PC.
I set these environment variables :
```
set ZBACKEND_FS_ROOT=C:\Projects\zenoh\data
set RUST_LOG=debug
```
and run zenoh server
`zenohd -c zenoh.json5`

The server seems to load the backend but then just exits without any apparent error or warning.  It also exits with the equivalent curl command in admin space:

```
C:\Projects\zenoh>zenohd -c zenoh.json5
[2021-12-17T14:44:34Z DEBUG zenohd] zenohd v0.6.0-dev-40-g19cbbcc built with rustc 1.57.0 (f1edd0429 2021-11-29)
[2021-12-17T14:44:34Z DEBUG zenohd] Config: Config { version: None, id: None, mode: Some(Router), peers: [], listeners: [Locator { address: Tcp(SocketAddr(0.0.0.0:7447)), metadata: None }], scouting: ScoutingConf { timeout: None, delay: None, multicast: ScoutingMulticastConf { enabled: Some(true), address: None, interface: None, autoconnect: None }, gossip: GossipConf { enabled: None, autoconnect: None } }, add_timestamp: Some(true), link_state: None, peers_autoconnect: None, local_routing: None, queries_default_timeout: None, join_on_startup: JoinConfig { subscriptions: [], publications: [] }, shared_memory: None, transport: TransportConf { sequence_number_resolution: None, qos: None, unicast: TransportUnicastConf { open_timeout: None, open_pending: None, max_sessions: None, max_links: None }, multicast: TransportMulticastConf { join_interval: None, max_sessions: None }, link: TransportLinkConf { batch_size: None, lease: None, keep_alive: None, rx_buff_size: None, defrag_buffer_size: None, tls: TLSConf { root_ca_certificate: None, server_private_key: None, server_certificate: None, client_auth: None, client_private_key: None, client_certificate: None } }, auth: AuthConf { usrpwd: UserConf { user: None, password: None, dictionary_file: None }, pubkey: PubKeyConf { public_key_pem: None, private_key_pem: None, public_key_file: None, private_key_file: None, key_size: None, known_keys_file: None } } }, plugins_search_dirs: [], plugins: Object({"rest": Object({"port": Number(8000)}), "storages": Object({"backends": Object({"fs": Object({"storages": Object({"demo": Object({"dir": String("data"), "key_expr": String("/demo/example/**"), "strip_prefix": String("/demo/example")})})})})})}) }
[2021-12-17T14:44:34Z INFO  zenohd] Initial conf: {"version":null,"id":null,"mode":"router","peers":[],"listeners":["tcp/0.0.0.0:7447"],"scouting":{"timeout":null,"delay":null,"multicast":{"enabled":true,"address":null,"interface":null,"autoconnect":null},"gossip":{"enabled":null,"autoconnect":null}},"add_timestamp":true,"link_state":null,"peers_autoconnect":null,"local_routing":null,"queries_default_timeout":null,"join_on_startup":{"subscriptions":[],"publications":[]},"shared_memory":null,"transport":{"sequence_number_resolution":null,"qos":null,"unicast":{"open_timeout":null,"open_pending":null,"max_sessions":null,"max_links":null},"multicast":{"join_interval":null,"max_sessions":null},"link":{"batch_size":null,"lease":null,"keep_alive":null,"rx_buff_size":null,"defrag_buffer_size":null,"tls":{"root_ca_certificate":null,"server_private_key":null,"server_certificate":null,"client_auth":null,"client_private_key":null,"client_certificate":null}},"auth":{"usrpwd":{"user":null,"password":null,"dictionary_file":null},"pubkey":{"public_key_pem":null,"private_key_pem":null,"public_key_file":null,"private_key_file":null,"key_size":null,"known_keys_file":null}}},"plugins_search_dirs":[],"plugins":{"rest":{"port":8000},"storages":{"backends":{"fs":{"storages":{"demo":{"dir":"data","key_expr":"/demo/example/**","strip_prefix":"/demo/example"}}}}}}}
[2021-12-17T14:44:34Z DEBUG zenoh_util::lib_loader] Search for library zplugin_rest.dll to load in ["\\\\?\\C:\\Projects\\zenoh"]
[2021-12-17T14:44:34Z DEBUG zenoh_util::lib_loader] Search for library zplugin_storages.dll to load in ["\\\\?\\C:\\Projects\\zenoh"]
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime] Using PID: AAC300CAE1F34CBABBD8E32556680C21
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::network] [Peers network] Add node (self) AAC300CAE1F34CBABBD8E32556680C21
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::network] [Routers network] Add node (self) AAC300CAE1F34CBABBD8E32556680C21
[2021-12-17T14:44:34Z DEBUG zenoh::net::runtime::orchestrator] Listener tcp/0.0.0.0:7447 added
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime::orchestrator] zenohd can be reached on tcp/169.254.87.47:7447
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime::orchestrator] zenohd can be reached on tcp/160.212.54.53:7447
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime::orchestrator] zenohd can be reached on tcp/169.254.111.241:7447
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime::orchestrator] zenohd can be reached on tcp/169.254.225.144:7447
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime::orchestrator] zenohd can be reached on tcp/169.254.60.134:7447
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime::orchestrator] zenohd can be reached on tcp/192.168.0.20:7447
[2021-12-17T14:44:34Z DEBUG zenoh::net::runtime::orchestrator] UDP port bound to 224.0.0.224:7447
[2021-12-17T14:44:34Z DEBUG zenoh::net::runtime::orchestrator] Joined multicast group 224.0.0.224 on interface 0.0.0.0
[2021-12-17T14:44:34Z INFO  zenoh::net::runtime::orchestrator] zenohd listening scout messages on 224.0.0.224:7447
[2021-12-17T14:44:34Z DEBUG zenoh::net::runtime::orchestrator] UDP port bound to 0.0.0.0:64463
[2021-12-17T14:44:34Z DEBUG zenoh::net::runtime::orchestrator] Waiting for UDP datagram...
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::router] New Face{0, AAC300CAE1F34CBABBD8E32556680C21}
[2021-12-17T14:44:34Z DEBUG zenoh_util::lib_loader] Cannot search for libraries in /usr/local/lib: The system cannot find the path specified. (os error 3)
[2021-12-17T14:44:34Z INFO  tide::server] Server listening on http://0.0.0.0:8000
[2021-12-17T14:44:34Z DEBUG zenoh_util::lib_loader] Cannot search for libraries in /usr/lib: The system cannot find the path specified. (os error 3)
[2021-12-17T14:44:34Z DEBUG zenoh_util::lib_loader] Cannot search for libraries in C:\Users\jnswart/.zenoh/lib: The system cannot find the file specified. (os error 2)
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::router] New Face{1, AAC300CAE1F34CBABBD8E32556680C21}
[2021-12-17T14:44:34Z DEBUG zenoh_util::lib_loader] Search for library zbackend_fs.dll to load in ["\\\\?\\C:\\Projects\\zenoh", "\\\\?\\C:\\Projects\\zenoh"]
[2021-12-17T14:44:34Z DEBUG zbackend_fs] FileSystem backend v0.6.0-dev-8-g85dd10d-modified built with rustc 1.57.0 (f1edd0429 2021-11-29)
[2021-12-17T14:44:34Z DEBUG zbackend_fs] Using root dir: \\?\C:\Projects\zenoh\data
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::resource] Register resource /@/router/AAC300CAE1F34CBABBD8E32556680C21/status/plugins/storages/backends/fs
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::queries] Register queryable /@/router/AAC300CAE1F34CBABBD8E32556680C21/status/plugins/storages/backends/fs (face: Face{1, AAC300CAE1F34CBABBD8E32556680C21}, kind: 4)
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::queries] Register router queryable /@/router/AAC300CAE1F34CBABBD8E32556680C21/status/plugins/storages/backends/fs (router: AAC300CAE1F34CBABBD8E32556680C21, kind:4)
[2021-12-17T14:44:34Z DEBUG zenoh::net::routing::queries] Register peer queryable /@/router/AAC300CAE1F34CBABBD8E32556680C21/status/plugins/storages/backends/fs (peer: AAC300CAE1F34CBABBD8E32556680C21, kind:4)

C:\Projects\zenoh>
```
The json5 config was copied from the Readme - with a small change (dir property).

Any help will be appreciated.

**Comment by JEnoch** [comment] 2021-12-20 11:28
I managed to find a Windows box to test this, and I confirm I reproduce the issue with both 0.5.0-beta.9 and 0.6.0-dev (master branch) versions.
No idea what could be the problem since there is no panic message, Rust backtrace or any sort of core dump !
I have no clue on how to debug this (no experience on Windows system debugging), except adding logs to try to narrow down the problem...

**Comment by JEnoch** [comment] 2021-12-21 10:21
I narrowed the issue down to [this line of code](https://github.com/eclipse-zenoh/zenoh/blob/a71407740d121275ff6be0ed1cf3da159f47b343/plugins/zenoh-plugin-storages/src/lib.rs#L243) where the storages plugin calls the [`Backend::incoming_data_interceptor()`](https://github.com/eclipse-zenoh/zenoh-backend-filesystem/blob/85dd10db6ed7b43b23a2f401689d364382d088d1/src/lib.rs#L234) function that the FileSystem backends trivially implements returning just `None` !
Still no clear idea on what's exactly causing the crash, and why only on Windows. I'll do more experiments in the next few days...

**Comment by lanner17** [comment] 2021-12-21 12:41
Ah, great that you could narrow it down. I figured it would be a hard one without any message or trace. Unfortunately my experience with the code is minimal and my Rust is beginning/intermediate, but I will also experiment.

**Comment by JEnoch** [comment] 2022-01-06 14:54
Debugging further, the crash appears when calling any of the Backend's trait operation (not only `incoming_data_interceptor()`). And it happens not only with `zenoh-backend-filesystem`, but also with any backend implementation on Windows - even a minimal one that just implement the Backend/Storage traits in a trivial way.

I finally found that Windows reports the crash in "Control panel > System and Security > Security and Maintenance > Problem Reports" : 
```
Source
zenohd.exe

Summary
Stopped working

Date
‎1/‎6/‎2022 6:42 AM

Status
Report sent

Description
Faulting Application Path: C:\Users\test\eclipse-zenoh\zenoh\target\debug\zenohd.exe

Problem signature
Problem Event Name: APPCRASH
Application Name: zenohd.exe
Application Version: 0.0.0.0
Application Timestamp: 61d5c4b0
Fault Module Name: zplugin_storages.dll
Fault Module Version: 0.0.0.0
Fault Module Timestamp: 61d6bced
Exception Code: c0000005
Exception Offset: 000000000005d494
OS Version: 10.0.19044.2.0.0.768.98
Locale ID: 1033
Additional Information 1: ee75
Additional Information 2: ee75e3d067434e319476fb4ba3071d8a
Additional Information 3: ed33
Additional Information 4: ed331da764bcd24521a171f142d74e70

Extra information about the problem
Bucket ID: 3f7bb08a5eade68f39ccacfb93331d75 (1859050942703541621)
```

No idea yet on how to analyse this...

**Comment by lanner17** [comment] 2022-01-07 14:35
I looked back in the event log on the Windows 10 PC and get the same (no surprise) :

```
Faulting application name: zenohd.exe, version: 0.0.0.0, time stamp: 0x61b9ea11
Faulting module name: zplugin_storages.dll, version: 0.0.0.0, time stamp: 0x61b9e9a1
Exception code: 0xc0000005
Fault offset: 0x0000000000047883
Faulting process id: 0x1bc4
Faulting application start time: 0x01d7f352e9ff89a7
Faulting application path: C:\Projects\zenoh\zenohd.exe
Faulting module path: \\?\C:\Projects\zenoh\zplugin_storages.dll
Report Id: 7fca98a6-df1e-4ccb-b30c-c6caf5d79e4b
Faulting package full name: 
Faulting package-relative application ID: 
```
Although I have never used it, I wonder if a  [user crash dump file](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps?redirectedfrom=MSDN) would be useful. The admin settings on my PC does not allow me to install the tools to analyze these files.

**Comment by JEnoch** [comment] 2022-01-10 16:41
I finally found the root of this issue:
the storages plugin correctly loads the backend library, but doesn't keep a reference on it. Thus, when it's dropped and probably unloaded when it goes out of scope and the Backend trait object becomes invalid.

The fix will come in the zenoh repository shortly.

**Comment by lanner17** [comment] 2022-01-10 17:24
That is great news. I look forward to try it out.

**Comment by JEnoch** [comment] 2022-01-10 17:47
The fix is pushed in zenoh repo: eclipse-zenoh/zenoh@06a51168
You must also pull the zenoh-backend-filesystem repo for the #7 fix.
And update your `zenoh.json5` to add the configuration of the rest plugin (see updated [README](https://github.com/eclipse-zenoh/zenoh-backend-filesystem/#setup-via-a-json5-configuration-file)), otherwise the REST plugin is not loaded and the `curl` commands will fail.

Please let me know if it works for you!

**Comment by lanner17** [comment] 2022-01-10 19:51
I pulled both zenoh and the backend with the fixes and rebuilt both. It works fine now with the examples in the README file.
Thank you for the fix.

This may be off topic now, but since I ran the examples, I will use the opportunity to throw in the question:

The curl command
`curl http://localhost:8000/demo/example/**`
returns 
```
[
{ "key": "/demo/example/test-1", "value": "VEVTVC0x", "encoding": "application/x-www-form-urlencoded", "time": "2022-01-10T19:43:16.377852000Z/1686F951462D413B86F07058A2F2EF2F" },
{ "key": "/demo/example/a/b", "value": "Qg==", "encoding": "application/x-www-form-urlencoded", "time": "2022-01-10T19:43:21.188697600Z/1686F951462D413B86F07058A2F2EF2F" }
]
```

I expected "TEST-1" and "B" for the two values. Does the discrepancy (in my view) have anything to do with the encoding ?

**Comment by JEnoch** [comment] 2022-01-11 15:59
Thanks for confirming the fix works!

By default `curl` sends the data with **application/x-www-form-urlencoded** encoding (see [`-d` option](https://linux.die.net/man/1/curl)). The REST plugin currently converts data with this encoding to base64 in GET replies.
I created eclipse-zenoh/zenoh#176 to change this.

**Closed by JEnoch** 2022-01-11 15:59 UTC
